### ISSUE TITLE
Misidentifying players with the same ID in one game

### ISSUE THREAD

**Issue by canuse** [Ledenel/auto-white-reimu#11]
Log: ```http://tenhou.net/0/?log=2019022817gm-0011-5574-e1a854ec&tw=1```
The game log above contains three different players with the same ID 'NoName'. The script ought to provide three different reasoning reports corresponding to each of the players when running "check result for all players", but it misidentifies the first player three times and only provides one report instead. (actually it overwrites the same output file for three times) 
Numbering the IDs or attach the seat order to the ID might be needed.

**Comment by Ledenel** [comment]
Now this should be fixed as #29 .
Player will get a extra id (NoName_0, NoName_1)
