### ISSUE TITLE
Add explanation to the TenhouRecord.game_list.events

### ISSUE THREAD

**Issue by canuse** [Ledenel/auto-white-reimu#13]
The current format of element 'event', which is like 'D70', 'U128'... , is quite hard to understand. It might be more readable if there is an explanation, namely 'deal 1s', 'discard 1s'.

**Comment by Ledenel** [comment]
Now the element 'event' is just plain XML Element parsed by native Python library `xml.etree.ElementTree` .

for better representation, we could:
1. add a wrapper, somthing like `TenhouEvent` for the XML Element.
2. in `TenhouEvent` delegate everything to thet real XML Element.
3. add some helper function and represention like `__str__` and `__repr__`.
4. hack [this point](https://github.com/Ledenel/auto-white-reimu/blob/7530abebdf1db08e4e0815167fd175f90835ec0d/mahjong/record/reader.py#L117) to ensure wrap any XML Element to `TenhouEvent`.

**Comment by Ledenel** [comment]
Would be something like this:

![image](https://user-images.githubusercontent.com/14890194/69360960-725d5a80-0cc6-11ea-9bcf-7a986c7308d1.png)

**Comment by Ledenel** [comment]
implemented at #15 .
